import { AppShell } from "./_components/AppShell";
import { getCoreHealth } from "../lib/open5gs/health";
import { nodes } from "../lib/network/catalog";

export default async function Home() {
  const health = await getCoreHealth();
  const healthy = health.networkFunctions.filter((item) => item.status === "healthy").length;
  const slugByName = new Map(nodes.map((node) => [node.name, node.slug]));

  return <AppShell section="overview">
    <header className="page-header"><div><p className="eyebrow">OPEN5GS · JAKARTA LAB</p><h1>Mobile core at a glance</h1><p className="subtle">One control center for your EPC and 5G Core networks.</p></div><div className="header-status"><span className={`pulse ${health.coreStatus === "unavailable" ? "offline" : ""}`} /><div><b>Core network {health.coreStatus}</b><small>{health.mode === "live" ? "Live agent" : "Demo data"}</small></div></div></header>
    <div className="metrics-grid"><article className="metric-card featured"><div className="metric-label">● NETWORK FUNCTIONS</div><strong>{health.networkFunctions.length}</strong><p><b>{healthy} healthy</b> · checked just now</p><div className="sparkline">{[35,48,44,60,55,72,68,82,76,92].map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div></article><article className="metric-card"><div className="metric-label">REGISTERED UE</div><strong>1,284</strong><p><b>+8.2%</b> from the previous hour</p></article><article className="metric-card"><div className="metric-label">PDU SESSIONS</div><strong>1,102</strong><p><b>85.8%</b> session rate</p></article><article className="metric-card"><div className="metric-label">USER PLANE</div><strong>2.48 <em>Gbps</em></strong><p><b>14%</b> below peak</p></article></div>
    <section className="core-selector"><a className="core-card epc-card" href="/epc"><div className="core-card-top"><span>4G</span><i>8 NODES</i></div><p className="eyebrow">EVOLVED PACKET CORE</p><h2>EPC Network</h2><p>MME, HSS, PCRF, SGW-C/U, and S/PGW in a unified topology.</p><div className="mini-flow"><b>UE</b><i /><b>eNB</b><i /><b>MME</b><i /><b>S/PGW</b></div><strong className="open-core">Open EPC topology →</strong></a><a className="core-card five-card" href="/5gc"><div className="core-card-top"><span>5G</span><i>5G SA</i></div><p className="eyebrow">SERVICE-BASED CORE</p><h2>5G Core Network</h2><p>UERANSIM, AMF, SMF, UPF, and all connected service-based functions.</p><div className="mini-flow"><b>gNB</b><i /><b>AMF</b><i /><b>SMF</b><i /><b>UPF</b></div><strong className="open-core">Open 5G topology →</strong></a></section>
    <section className="panel overview-nodes" id="events"><div className="panel-head"><div><p className="eyebrow">LIVE HEALTH</p><h2>Network functions</h2></div><span className="live"><i /> LIVE</span></div><div className="health-grid">{health.networkFunctions.map((item) => <a href={`/nodes/${slugByName.get(item.name) ?? item.name.toLowerCase()}`} key={item.name}><span className="nf-monogram">{item.name.slice(0, 2)}</span><div><b>{item.name}</b><small>{item.role}</small></div><em>{item.latencyMs == null ? "—" : `${item.latencyMs} ms`}</em><span className={`status ${item.status}`}><i />{item.status}</span></a>)}</div></section>
  </AppShell>;
}
